name: Artifacts Demo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: File banao
        run: |
          echo "Build Result!" > build-result.txt
          echo "Test Passed!" > test-result.txt

      - name: Artifact upload karo
        uses: actions/upload-artifact@v4
        with:
          name: my-artifacts
          path: |
            build-result.txt
            test-result.txt
         
