name: Caller Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-dev:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      environment: "Development"

  deploy-prod:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      environment: "Production"
