name: GitHub Packages Demo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Package banao
        run: |
          mkdir -p dist
          echo "My Package v1.0" > dist/package.txt
          echo "Created by Riya!" >> dist/package.txt

      - name: Artifact upload karo
        uses: actions/upload-artifact@v4
        with:
          name: my-package
          path: dist/
