name: Environment Protection Demo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v6

      - name: Production Deploy
        run: echo "Deploying to Production!"
