name: Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6

      - name: Deploy karo
        run: echo "Deploying to ${{ inputs.environment }}!"
