name: Secrets Demo
on:
  push:
    branches:
      - dev
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Secret use karo
        run: echo "My secret is ${{ secrets.MY_SECRET_MESSAGE }}"
      - name: Done
        run: echo "Secrets kaam kar rahe hain!"